[toolchain]
anchor_version = "0.30.0"
solana-version = "1.18.16"

[features]
resolution = true
skip-lint = false

[programs.devnet]
my_token = "AaDFYp7PaMSPNdtA5B1fNEKvfNLLjAF3hMVUqZVhe1BF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/tokenizer/code/wallet/keypair1.json"

[scripts]
test = "npx jest"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
