[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_token = "AaDFYp7PaMSPNdtA5B1fNEKvfNLLjAF3hMVUqZVhe1BF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
