[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
my_token = "4q9zSqGHPwFquwgfMRMtsFWnFZYBzWbRFESXcAMyH4cE"

[programs.localnet]
my_token = "4q9zSqGHPwFquwgfMRMtsFWnFZYBzWbRFESXcAMyH4cE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/tokenizer/code/wallet/keypair2.json"

[scripts]
test = "npx jest"
